### ISSUE TITLE
Error with Filter by index type

### ISSUE THREAD

**Issue by Daniel-Trung-Nguyen** [davemlz/espectro#1]
I found this error when filtering by index type
![image](https://user-images.githubusercontent.com/22897462/181522709-68877295-647c-49dc-9b97-1552eb3e7378.png)

**Comment by davemlz** [comment]
Ohh, thanks for spotting this! I'm on it :)

**Comment by davemlz** [comment]
The error was fixed and the app is rebooting. Soon it will be available again. Thank you!
