### ISSUE TITLE
Espectro Streamlit app error

### ISSUE THREAD

**Issue by RachelRS17** [davemlz/espectro#2]
Not sure if Espectro Streamlit app still being supported / developed, but following error occurs when try to filter:

![Screenshot 2024-02-04 125900](https://github.com/awesome-spectral-indices/espectro/assets/158823874/c715d79d-20f8-4bbe-8457-fed2e273e7a3)

Thanks!

**Comment by robmarkcole** [comment]
Still an issue

**Comment by davemlz** [comment]
The App is up again! ;)
